### ISSUE TITLE
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres: 3 pts

### ISSUE THREAD

**Issue by fmhoeger** [Dallinger/Dallinger#2856]
Sandboxing/deploying an experiment fails when applying the `--archive` option.

## Expected Behavior
It should sandbox/deploy an experiment from a previously exported snapshot ZIP file. 

## Current Behavior
`dallinger sandbox --archive data/data-rhyrat1/db-snapshot/rhyrat1-data.zip --app rhyrat` fails with
```
❯❯ Ingesting dataset from rhyrat1-data.zip...
Traceback (most recent call last):
  File "/home/frank/.virtualenvs/psynet/bin/dallinger", line 33, in <module>
    sys.exit(load_entry_point('dallinger', 'console_scripts', 'dallinger')())
  File "/home/frank/.virtualenvs/psynet/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/frank/.virtualenvs/psynet/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/frank/.virtualenvs/psynet/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frank/.virtualenvs/psynet/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frank/.virtualenvs/psynet/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/frank/projects/Dallinger/dallinger/command_line/utils.py", line 72, in wrapper
    return f(**kwargs)
  File "/home/frank/projects/Dallinger/dallinger/command_line/__init__.py", line 99, in wrapper
    result = func(*args, **kwargs)
  File "/home/frank/projects/Dallinger/dallinger/command_line/__init__.py", line 264, in sandbox
    _deploy_in_mode(mode="sandbox", verbose=verbose, log=log, app=app, archive=archive)
  File "/home/frank/projects/Dallinger/dallinger/command_line/__init__.py", line 251, in _deploy_in_mode
    deploy_sandbox_shared_setup(
  File "/home/frank/projects/Dallinger/dallinger/deployment.py", line 618, in deploy_sandbox_shared_setup
    task(heroku_app, config)
  File "/home/frank/projects/Dallinger/dallinger/command_line/__init__.py", line 227, in bootstrap_db
    engine = db.create_db_engine(heroku_app.db_url)
  File "/home/frank/projects/Dallinger/dallinger/db.py", line 57, in create_db_engine
    return create_engine(db_url, pool_size=pool_size)
  File "<string>", line 2, in create_engine
  File "/home/frank/.virtualenvs/psynet/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/home/frank/.virtualenvs/psynet/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 522, in create_engine
    entrypoint = u._get_entrypoint()
  File "/home/frank/.virtualenvs/psynet/lib/python3.9/site-packages/sqlalchemy/engine/url.py", line 653, in _get_entrypoint
    cls = registry.load(name)
  File "/home/frank/.virtualenvs/psynet/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 339, in load
    raise exc.NoSuchModuleError(
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres
```
## Your Environment

* Dallinger version used: 7.2.1

**Comment by silviot** [comment]
The dialect for postgres in sqlalchemy [changed name from postgres to postgresql](https://docs.sqlalchemy.org/en/14/changelog/changelog_14.html#change-3687655465c25a39b968b4f5f6e9170b) in sqlalchemy 1.4 (released in March 2021). Experiments exported before dallinger adopted the change will use the wong URL.
Dallinger should fix this automatically.
While this is not fixed you can try to edit the `config.txt` file inside the zip file, fixing the postgresql url.
You need to replace `postgres://` with `postgresql://`.

**Comment by fmhoeger** [comment]
This seems to still happen with Dallinger v7.6.0:

`dallinger sandbox --app fh-archive-deploy --archive data/data-fh-archive-test/db-snapshot/fh-archive-test-data.zip`

```
❯❯ Ingesting dataset from fh-archive-test-data.zip...
Traceback (most recent call last):
  File "/home/frank/.virtualenvs/psynet/bin/psynet", line 33, in <module>
    sys.exit(load_entry_point('psynet', 'console_scripts', 'psynet')())
  File "/home/frank/.virtualenvs/psynet/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/frank/.virtualenvs/psynet/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/frank/.virtualenvs/psynet/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frank/.virtualenvs/psynet/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frank/.virtualenvs/psynet/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/frank/.virtualenvs/psynet/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frank/projects/psynet/psynet/command_line.py", line 191, in sandbox
    ctx.invoke(dallinger_sandbox, verbose=verbose, app=app, archive=archive)
  File "/home/frank/.virtualenvs/psynet/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/frank/projects/Dallinger/dallinger/command_line/utils.py", line 72, in wrapper
    return f(**kwargs)
  File "/home/frank/projects/Dallinger/dallinger/command_line/__init__.py", line 264, in wrapper
    return f(**kwargs)
  File "/home/frank/projects/Dallinger/dallinger/command_line/__init__.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "/home/frank/projects/Dallinger/dallinger/command_line/__init__.py", line 278, in sandbox
    _deploy_in_mode(mode="sandbox", verbose=verbose, log=log, app=app, archive=archive)
  File "/home/frank/projects/Dallinger/dallinger/command_line/__init__.py", line 244, in _deploy_in_mode
    deploy_sandbox_shared_setup(
  File "/home/frank/projects/Dallinger/dallinger/deployment.py", line 216, in deploy_sandbox_shared_setup
    task(heroku_app, config)
  File "/home/frank/projects/Dallinger/dallinger/command_line/__init__.py", line 220, in bootstrap_db
    engine = db.create_db_engine(heroku_app.db_url)
  File "/home/frank/projects/Dallinger/dallinger/db.py", line 61, in create_db_engine
    return create_engine(db_url, pool_size=pool_size)
  File "<string>", line 2, in create_engine
  File "/home/frank/.virtualenvs/psynet/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/home/frank/.virtualenvs/psynet/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 522, in create_engine
    entrypoint = u._get_entrypoint()
  File "/home/frank/.virtualenvs/psynet/lib/python3.9/site-packages/sqlalchemy/engine/url.py", line 636, in _get_entrypoint
    cls = registry.load(name)
  File "/home/frank/.virtualenvs/psynet/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 343, in load
    raise exc.NoSuchModuleError(
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres
```
```
$ dallinger -v
7.6.0
```

**Comment by pmcharrison** [comment]
Closed as completed
